# Site settings

author: haipv1108
email: haipv1108@email.com
twitter_username: haipv1108
github_username:  haipv1108
googleplus_username: haipv1108

head-title: ferretOne Members
title: ferretOne Members Docs

baseurl: ""    # the subpath of your site, "/blog"
url: ""

# footer
description: "日本における99.7%の企業の問題解決をするのが私たちベーシックです。"

favo: "Webマーケティングを世界一簡単に"
descrpt: "僕らはWebマーケティングの大衆化を実現させる"


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 10
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt
